#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3 4 5 
bspc monitor DP-0 -d 6 7 8 9 10
#bspc monitor DP-0 -s DP-1

bspc desktop 2 --layout monocle

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focused_border_color "#80c484"

bspc config external_rules_command ~/bin/external_rules.sh

#bspc config ignore_ewmh_focus true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox  border=off 



# Apps on Floating Mode

bspc rule -a xdman-Main state=floating


# Start Apps on specific workspace

bspc rule -a firefox desktop='^2' follow=off
bspc rule -a brave desktop='^3' follow=off 
bspc rule -a qBittorrent desktop='^7' follow=off
bspc rule -a discord desktop='^8' follow=off
bspc rule -a Org.gnome.Nautilus desktop='^4' follow=off
bspc rule -a TelegramDesktop desktop='^9' follow=off
bspc rule -a m_on_browser desktop='^10' follow=off
bspc rule -a notion-app-enhanced desktop='^6' follow=off

bspc rule -a copyq state=floating hidden=on


bspc rule -a time_terminal rectangle=400x250+0+0 state=floating center=true sticky=on --f hidden=on 
bspc rule -a task_manager rectangle=1200x700+0+0 state=floating center=true

### Startup 

#$HOME/bin/polybar.sh
#$HOME/bin/multi_monitor_script
$HOME/.config/bspwm/autostart
$HOME/bin/volume-rocker
