#!/bin/bash

if [[ ! -f "/usr/local/lib/spotify-adblock.so" ]]; then
  sudo pacman -S spotify --noconfirm
  git clone https://github.com/abba23/spotify-adblock.git
  cd spotify-adblock
  make
  sudo make install
  cd ..
  rm -rf spotify-adblock
fi
